### ISSUE TITLE
Monitoring the sleeping time

### ISSUE THREAD

**Issue by lgs001elite** [NessieCircuits/Riotee_SDK#10]
It is not clear to measure the sleeping time of Riotees.

**Comment by geissdoerfer** [comment]
This is currently not implemented. RTC0 is a free running 32khz timer that you could use to take timestamps. You would timestamp the moment the device is put to sleep (e.g. in teardown callback) and timestamp the moment the device wakes up again. The difference would yield the time the device has been sleeping (if no reset occurred in between).

**Comment by lgs001elite** [comment]
Cool. But I still have two questions.
1. I notice the Counter is uint32, will it overflow when I count the interval between sleep off and sleep on?
2.  You said, "The difference would yield the time the device has been sleeping (if no reset occurred in between).". I want to know what's the reset. a:  is a timer (RTC) reset?   b: is a system reset? (I understand that the system reset is the process from the sleeping state to the active state. )

**Comment by geissdoerfer** [comment]
> Cool. But I still have two questions.
> 
>     1. I notice the Counter is uint32, will it overflow when I count the interval between sleep off and sleep on?
> 
In fact, it is only a 24-bit counter (see nRF PS section on RTC) and yes, it will overflow after 512s. Better timestamping would definitely be useful, so please feel free to open an issue asking for timestamping of internal RTC and I will try to implement it asap.

>     2. You said, "The difference would yield the time the device has been sleeping (if no reset occurred in between).". I want to know what's the reset. a:  is a timer (RTC) reset?   b: is a system reset? (I understand that the system reset is the process from the sleeping state to the active state. )

I mean a system reset, i.e. loss of all volatile memory. Such reset does not occur when transitioning from sleeping state to active state. It will occur after a complete power loss. When capacitor voltage gets low, the system will transition to sleep. But if the harvested energy is very low or zero, the power supply will eventually cease. When power returns, the system will be reset.

**Comment by geissdoerfer** [comment]
I just added `riotee_timing_now(uint64_t *)`. It takes a timestamp of the RTC0 clock extended to 56bits. This doesn't overflow anytime soon ;)

You can check the return code of that function to see if a reset has occured since the last call. If it returns `RIOTEE_SUCCESS` you can safely subtract two timestamps to get a duration.

Hope that helps!

**Comment by lgs001elite** [comment]
Ticks transfer to timer.
1. In riotee_sleep_ms() function. You said ticks = ms * 32768/1000. I can get 1ms = 327.68 ticks.  However, in sys_setup_timer()
you set 10 ms with ticks 8333. It is bigger than 3266.8 (327.68 * 10). I observe the two functions have the same left shift rules.
![image](https://github.com/NessieCircuits/Riotee_SDK/assets/65667947/b68ff7f3-7133-4eb6-8a40-44fddd083063)
![image](https://github.com/NessieCircuits/Riotee_SDK/assets/65667947/5711f84e-c23a-483b-9580-d56bff279ebd)

2.  riotee_timing_now(). It is really a good function. I am testing it.

**Comment by geissdoerfer** [comment]
1ms=32.768 ticks. And you're right, there is something wrong with the call to sys_setup_timer(). I will have a look at it.
