### ISSUE TITLE
Checkingpoint with BLE

### ISSUE THREAD

**Issue by lgs001elite** [NessieCircuits/Riotee_SDK#12]
Hi Kai,
I want to do BLE communication in Riotees. Theoretically, I just used the Nordic chips, for example, the BLE demo in the doc. Will the system do checkpointing when the system drops into the sleeping state?

**Comment by geissdoerfer** [comment]
Yes, if you use the Riotee BLE API, the system will abort the transmission and checkpoint the application state when the energy becomes critically low.

**Comment by lgs001elite** [comment]
Where is the state stored? It is in FRAM on MSP or an individual flash?

**Comment by geissdoerfer** [comment]
It is stored in the FRAM on the MSP430. You can read more about this [here](https://www.riotee.nessie-circuits.de/docs/latest/software/runtime.html).
