### ISSUE TITLE
General Oddities & Improvements

### ISSUE THREAD

**Issue by orgua** [NessieCircuits/Riotee_SDK#2]
things I found working with the examples (work in progress): 

- it should be enough to include `riotee.h` (+drivers) in user-code, as all source files get compiled anyway (even drivers), but this currently throws a linker error
- startup_ and reset_callback names are misleading - a bit more documentation would be nice. Are these call-chains below correct?
  - after flash: bootstrap, startup, reset
  - after powerdown: startup, reset
  - how about calling them startup_early, startup_late?
- the callbacks should also get documentation in source-code to allow IDE-hints
  - similar to [here](https://www.riotee.nessie-circuits.de/docs/latest/software/runtime/)
  - startup_callback can completely fail if something like printf() is done there (don't ask how I know)
- vm1010-example - adc gets initialized in example-, but used in driver-code -> strange
-

**Comment by geissdoerfer** [comment]
Thanks for reporting!
> things I found working with the examples (work in progress):
> 
>     * it should be enough to include `riotee.h` (+drivers) in user-code, as all source files get compiled anyway (even drivers), but this currently throws a linker error
This seems to work in the [examples](https://github.com/NessieCircuits/Riotee_SDK/blob/main/examples/stella/src/main.c). Could you give an example, where error occurs?
> 
>     * startup_ and reset_callback names are misleading - a bit more documentation would be nice. Are these call-chains below correct?
>       
>       * after flash: bootstrap, startup, reset
>       * after powerdown: startup, reset
>       * how about calling them startup_early, startup_late?
> 
Not quite: bootstrap is called after startup ;) But the list is good and I'll put it somewhere in the docs. I'll also try to think of better names.
>     * the callbacks should also get documentation in source-code to allow IDE-hints
>       
[Done!](https://github.com/NessieCircuits/Riotee_SDK/commit/02ddf9902c9e9cbc1e1b9c362178a679d61e510b)
>       * similar to [here](https://www.riotee.nessie-circuits.de/docs/latest/software/runtime/)
>       * startup_callback can completely fail if something like printf() is done there (don't ask how I know)
> 
>     * vm1010-example - adc gets initialized in example-, but used in driver-code -> strange
[Done!](https://github.com/NessieCircuits/Riotee_SDK/commit/3f6ffc705f390cdff15a0014f04a3b359fec2651)
