### ISSUE TITLE
riotee_wait_cap_charged() can deadlock the system

### ISSUE THREAD

**Issue by orgua** [NessieCircuits/Riotee_SDK#3]
Example-Code 
- spamming the mentioned function 
- board gets enough solar energy (all 4 cells) and has caps 1to6 enabled
- output stops sporadically (usually < 100 calls)
- no recovery until energy is removed (and turnoff is called)
  - not even partly dis- and recharging cap  

```
#include "riotee.h"
#include "riotee_timing.h"
#include "riotee_uart.h"
#include "printf.h"
#include "riotee_gpio.h"

#include "shtc3.h"
#include "vm1010.h"

#define PIN_MICROPHONE_DISABLE PIN_D5

void startup_callback(void) {
  //printf("Started\r\n");
  shtc3_init();
  riotee_gpio_cfg_output(PIN_MICROPHONE_DISABLE);
  riotee_gpio_set(PIN_MICROPHONE_DISABLE);
}

/* This gets called after every reset */
void reset_callback(void) {
  printf("  Reset\r\n");
}

void turnoff_callback(void) {
  printf("    Turnoff\r\n");
  /* Disable the microphone */
  riotee_gpio_set(PIN_MICROPHONE_DISABLE);
}

int main(void) {
  int counter = 0;
  printf("Main entered\r\n");

  for (;;) {

    riotee_sleep_ticks(70);  // this accelerates the problem 
    riotee_wait_cap_charged();
    printf("C%d, ", counter++);
    //riotee_sleep_ms(200);
  }
}
```

Console-Output
- four tries ended at C75, C69, C93, C88

```
\0  Reset
Main entered
C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, 
[]
```

Trace-Plot

![Screenshot 2023-07-11 171303](https://github.com/NessieCircuits/Riotee_Runtime/assets/1045108/351733bc-b1a4-4ba0-8242-2a0549bb16d9)

**Comment by geissdoerfer** [comment]
Thanks for reporting! I just tried to reproduce this multiple times, while switching on and off power supplies without success. Also tested an older code version (a8866728a902ea5b3cee677f810f0acd0ec9fc15) without issues. I get counter values way above 10000 with correct checkpointing/restoring and everything.

Could you please try again with the latest code and let me know if you're still experiencing problems?

**Comment by geissdoerfer** [comment]
@orgua, would you have time to check that real quick?

**Comment by geissdoerfer** [comment]
Cannot be reproduced and no reply from @orgua

**Comment by orgua** [comment]
After testing it again today the original issue seems fixed! This runs now indefinitely - no deadlock during runtime anymore.
