### ISSUE TITLE
Zigbee?

### ISSUE THREAD

**Issue by KanyonKris** [NessieCircuits/Riotee_SDK#4]
Zigbee was mentioned in the crowd funding campaign. Do you have an estimate release date?

**Comment by geissdoerfer** [comment]
Hi, you're right, the table lists Zigbee as one of the radio standards supported by the nRF52 radio. Networking on battery-free devices remains a hot topic of bleeding edge research. Implementing the Zigbee stack on Riotee would be an interesting but highly challenging task. We currently don't have plans for it but we are happy to support any efforts in that direction.

Under *limitations*, we mention that we currently only support BLE advertising and a custom protocol for bidirectional data exchange with a gateway (Stella). Could any of these work for your use case?

**Comment by KanyonKris** [comment]
Zigbee would be the best protocol for me. But I can understand it may not be possible in a ultra-low power energy harvesting device. I'll try BLE and Stella.
