### ISSUE TITLE
Example program not working

### ISSUE THREAD

**Issue by KanyonKris** [NessieCircuits/Riotee_SDK#5]
I'm getting no blinking LED from the example program.

I installed Arduino 2.1.1. Installed the Riotee boards 0.1.0. Copied the example program into the Arduino IDE editor:

```
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  riotee_wait_cap_charged();
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1);
  digitalWrite(LED_BUILTIN, LOW);
}
```
The program compiled and uploaded to the Riotee board. Switched both DIP switches on the solar board to ON. Put the board under some lights, the Vin measured over 0.25V. The LED on the board didn't blink. I'll try the board in the sun tomorrow (it's night now). But from what I've read the LED should have blinked powered by my indoor lights.
Kind of disappointing to get a new toy and not get it to work. Have I missed something?

**Comment by geissdoerfer** [comment]
It sounds like you did everything right. The device should definitely also perform under (sufficient) indoor light. Just make sure to watch the red LED on the module right next to the metal shield and not the green board LED.

Let me know if you're still having problems outside. I'll be back on my desk tomorrow and can test the code.

**Comment by KanyonKris** [comment]
Thanks for the reply. I was watching the wrong LED (the green one on the Riotee board). I now see the red LED on the Riotee module lighting up. I suggest you update the Get Started page to clearly specify the correct LED. And update the Riotee board and module hardware pages to identify the LEDs and other main components.
![image](https://github.com/NessieCircuits/Riotee_SDK/assets/5475317/e2777350-7962-4b96-93d0-ab47bea7c382)

**Comment by geissdoerfer** [comment]
Great! And thanks for the suggestions, I'll update the docs accordingly.
