### ISSUE TITLE
Forum?

### ISSUE THREAD

**Issue by KanyonKris** [NessieCircuits/Riotee_SDK#6]
Where should Riotee users discuss and share info with each other? Here in the Github issues or some other forum?

**Comment by geissdoerfer** [comment]
Thanks for raising this. I just set up a [discord server](https://discord.gg/7zVVJB2E). I hope this will take off :)

**Comment by Nehesh-S** [comment]
Hey,
The invite link is expired. Is there a new forum or Invite link somewhere?

**Comment by geissdoerfer** [comment]
Hi @Nehesh-S! Unfortunately, there hasn't developed any community on the discord server. Is there anything specific you're looking for or did you just want to meet other Riotee users?

**Comment by Nehesh-S** [comment]
A little bit of both! I would love to connect with other Riotee users and developers through the means of a forum. That will also be great to discuss issues and share project ideas imo.

**Comment by geissdoerfer** [comment]
Yeah I did have the discord up for a year and no one signed up. So while I could give you the link, you wouldn't really find anyone there. Currently most users are universities who get in touch with me directly.

**Comment by avonkannewurff** [comment]
I am also interested in connecting with others, just set up the blink demo with my board!

**Comment by geissdoerfer** [comment]
Well, feel free to join the discord then :) Here's a new invite link: https://discord.gg/xPEj2WSB
