### ISSUE TITLE
Arduino Board Manager Install Error

### ISSUE THREAD

**Issue by tamberg** [NessieCircuits/Riotee_SDK#8]
Installing the Riotee Arduino Board Manager (0.2.0 or earlier) seems to lead to an error (IDE 1.8.19):

<img width="912" alt="Screenshot 2023-09-04 at 17 51 04" src="https://github.com/NessieCircuits/Riotee_SDK/assets/142092/e26c915d-45c5-482d-8f56-8f446130e6e2">

**Comment by tamberg** [comment]
https://www.riotee.nessie-circuits.de/arduino/package_riotee_index.json

```
...
"tools": [
        {
          "name": "gcc-arm-none-eabi",
          "version": "12.2.0",
          "systems": [
            {
              "host": "x86_64-apple-darwin14",
              "url": "https://riotee.nessie-circuits.de/arduino/tools/arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi.tar.gz",
              "archiveFileName": "arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi.tar.gz",
              "size": "215065991",
              "checksum": "MD5:7c981baea377f91bdfeb3a93e19dba6f"
            },
            ...
```

https://www.riotee.nessie-circuits.de/arduino/tools/arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi.tar.gz => 404
```
$ curl -v https://www.riotee.nessie-circuits.de/arduino/tools/arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi.tar.gz
*   Trying 82.100.220.62:443...
* Connected to www.riotee.nessie-circuits.de (82.100.220.62) port 443 (#0)
...
< HTTP/1.1 404 Not Found
```

**Comment by geissdoerfer** [comment]
Thanks for reporting. I just uploaded the toolchain, could you please try again?

**Comment by tamberg** [comment]
Thanks! Installing works. Board shows up:

<img width="564" alt="Screenshot 2023-09-04 at 18 16 15" src="https://github.com/NessieCircuits/Riotee_SDK/assets/142092/f8853c35-d1ab-453d-ab65-3e373616dfe1">

**Comment by tamberg** [comment]
However, after selecting the Riotee Board, examples do not show up in Files > Examples > Examples for Riotee Board:

<img width="476" alt="Screenshot 2023-09-04 at 18 20 00" src="https://github.com/NessieCircuits/Riotee_SDK/assets/142092/8c69881d-678e-4f7d-adce-617c5ee3f48e">

(Not sure if this is intended?)

**Comment by geissdoerfer** [comment]
Well, it is expected as we don't provide Arduino examples, yet. It is on my todo list, though. Feel free to open an issue requesting Arduino examples to raise the priority ;)

**Comment by geissdoerfer** [comment]
This is currently all we have in terms of Arduino documentation: https://www.riotee.nessie-circuits.de/docs/latest/software/arduino.html
